name: github pages

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository
        id: version
        run: |
          REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo ::set-output name=repository::$REPOSITORY
      - name: Create dot env file
        run: |
          touch .env
          echo "QIITA_TOKEN=${{ secrets.QIITA_TOKEN }}" >> .env
      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.5"
          channel: "stable"
          cache: true
      - run: flutter --version
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter build web --web-renderer html --base-href /${{ steps.version.outputs.repository }}/
      - uses: actions/upload-pages-artifact@v1
        with:
          path: build/web
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
